create table if not exists public.input_db (
  id bigint generated by default as identity primary key,
  input_text text not null,
  created_at timestamptz not null default now()
);

alter table public.input_db enable row level security;

create policy "Anyone can insert test input"
on public.input_db
for insert
to anon
with check (true);

create policy "Anyone can read test input"
on public.input_db
for select
to anon
using (true);
